"""chnages in media class

Revision ID: 53714f0969d4
Revises: bed7985d2696
Create Date: 2023-07-17 11:20:17.958239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53714f0969d4'
down_revision = 'bed7985d2696'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('photo_dir', sa.String(), nullable=True))
    op.add_column('medias', sa.Column('video_dir', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medias', 'video_dir')
    op.drop_column('medias', 'photo_dir')
    # ### end Alembic commands ###
