"""del model button

Revision ID: 5fc4e8545b7d
Revises: 910c147071c4
Create Date: 2023-07-18 02:50:34.020447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc4e8545b7d'
down_revision = '910c147071c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buttons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('button_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('button_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='buttons_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='buttons_pkey')
    )
    # ### end Alembic commands ###
