"""only one button for post

Revision ID: 910c147071c4
Revises: c9f9048ba2b5
Create Date: 2023-07-18 02:40:09.825831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910c147071c4'
down_revision = 'c9f9048ba2b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('button_name', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('button_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'button_url')
    op.drop_column('posts', 'button_name')
    # ### end Alembic commands ###
