"""only one photo or video

Revision ID: c9f9048ba2b5
Revises: b9af946f85f5
Create Date: 2023-07-18 00:49:46.303817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f9048ba2b5'
down_revision = 'b9af946f85f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medias')
    op.add_column('posts', sa.Column('photo_dir', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('video_dir', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('video_url', sa.String(), nullable=True))
    op.drop_column('posts', 'is_media_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_media_group', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'video_url')
    op.drop_column('posts', 'video_dir')
    op.drop_column('posts', 'photo_url')
    op.drop_column('posts', 'photo_dir')
    op.create_table('medias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_dir', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video_dir', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='medias_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='medias_pkey')
    )
    # ### end Alembic commands ###
